### ISSUE TITLE
Should it be templates.yaml instead of template.yaml?

### ISSUE THREAD

**Issue by pavelanni** [chrisvoncsefalvay/cookiecutter-flask-ask#2]
Hi Chris,

Thanks for this cookiecutter, really helpful. One small thing: my skill failed to run and gave me the "TypeError: Can't compile non template nodes" until I renamed 'template.yaml' to 'templates.yaml'.
I don't know if the name can be configured in Flask-Ask itself, but it looks like by default it expects 'templates.yaml'.

**Comment by chrisvoncsefalvay** [comment]
Fixed in Commit #3f70514 :) Good spot!
